/**
 * Workspace Predictions Controller
 *
 * GET /api/workspaces/:workspaceId/predictions
 *   ?days=90   (optional, default 90, max 365)
 *
 * Returns time-series productivity predictions, a 7×24 activity heatmap,
 * and actionable insight strings generated by K-Means clustering.
 */
import { isValidObjectId } from "../utils/validators.js";
import { getWorkspaceMembership } from "../utils/access.js";
import { generateWorkspacePredictions } from "../services/productivityPredictionService.js";
import logger from "../utils/logger.js";

export const getWorkspacePredictions = async (req, res) => {
  try {
    const { workspaceId } = req.params;
    const userId = req.user?.id;

    if (!isValidObjectId(workspaceId)) {
      return res.status(400).json({ message: "Invalid workspace id" });
    }

    // Verify the caller has access to this workspace
    const membership = await getWorkspaceMembership(workspaceId, userId);
    if (!membership) {
      return res
        .status(404)
        .json({ message: "Workspace not found or not accessible" });
    }

    const rawDays = Number(req.query.days);
    const days = Number.isFinite(rawDays) && rawDays > 0
      ? Math.min(Math.floor(rawDays), 365)
      : 90;

    const predictions = await generateWorkspacePredictions(workspaceId, {
      days,
    });

    return res.status(200).json(predictions);
  } catch (error) {
    logger.error("Workspace predictions endpoint error", {
      message: error?.message,
    });
    return res.status(500).json({ message: "Internal server error" });
  }
};

export default { getWorkspacePredictions };
